### ISSUE TITLE
FriendlyMenu stays on screen if right clicking group member

### ISSUE THREAD

**Issue by samera999** [samera999/SWLRP-Flash#2]
Issued by spell.  Looking into it when I can.

**Comment by spellsmith** [comment]
Correction:  it's not that it stays on screen, it's that it appears in the wrong place.  If you DO NOT have the mod installed, the Friendly Menu appears basically wherever you're right-clickign.  If you DO have the mod installed, it appears in th emiddle of your screen no matter what.  

See screenshots.  This is having Null-State in group and right-clicking on her name.

![with_mod](https://user-images.githubusercontent.com/30157296/29753457-a444fde0-8b37-11e7-9270-6cdb5dfbd488.jpg)

![without_mod](https://user-images.githubusercontent.com/30157296/29753458-a445a11e-8b37-11e7-85c8-166d7691b6ae.jpg)

**Comment by samera999** [comment]
I edited friendlymenu to fix this issue.
